name: Demo Secreta

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Ova linija povezuje kod sa tvojim okruženjem i aktivira odobrenje:
    environment: production
    
    steps:
      - name: Deploy u produkciju
        env:
          KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "Deployujem u produkciju..."
          echo "Ključ je uspješno povučen iz Environments!"
